---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: result
  namespace: instavote
spec:
  chart:
    spec:
      chart: ./deploy/charts/result
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: instavote
  interval: 1m0s
  targetNamespace: instavote
