---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: worker-staging
  namespace: flux-system
spec:
  dependsOn: 
  # kustomization
  - name: redis-staging
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s
