apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: vote
  namespace: instavote
spec:
  analysis:
    # for blue/green deployment
    # interval: 30s
    # threshold: 3
    # iterations: 5

    # for canary deployment
    interval: 10s
    threshold: 10
    maxWeight: 50
    stepWeight: 5