apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  minReadySeconds: 20
  replicas: 3
  template:
    spec:
      containers:
        - image: schoolofdevops/vote:v5
          name: vote
          envFrom:
            - configMapRef:
                # name: vote
                name: vote-options
                optional: true

